/*
Package chat contains the core logic for handling real-time chat rooms, user connections, and message broadcasting.

This file defines the special user identity used for sending system messages.
*/
package chat

import "hzchat/internal/app/user"

// SystemUser represents the identity of the sender for system messages.
// This identity is used to mark messages generated by the server, such as
// user join/leave notifications and error messages.
var SystemUser = user.User{
	ID:       "system",
	Nickname: "system",
	Avatar:   "",
}
