// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID            pgtype.UUID        `json:"id"`
	Username      string             `json:"username"`
	PasswordHash  string             `json:"password_hash"`
	Email         pgtype.Text        `json:"email"`
	Nickname      pgtype.Text        `json:"nickname"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	PlanType      string             `json:"plan_type"`
	PlanExpiresAt pgtype.Timestamptz `json:"plan_expires_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
