// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Registers a new user with core credentials.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Retrieves a user's display profile and service plan by their UUID.
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	// Retrieves an active user by their username for authentication purposes.
	// Only returns users who have not been soft-deleted.
	GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error)
	// Updates the last login timestamp for a specific user.
	UpdateLastLogin(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
