// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, 
    password_hash, 
    nickname
) VALUES (
    $1, $2, $3
)
RETURNING id, username, password_hash, email, nickname, avatar_url, plan_type, plan_expires_at, created_at, updated_at, last_login_at, deleted_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Nickname     pgtype.Text `json:"nickname"`
}

// Registers a new user with core credentials.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.PasswordHash, arg.Nickname)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Nickname,
		&i.AvatarUrl,
		&i.PlanType,
		&i.PlanExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    id, 
    nickname, 
    avatar_url, 
    plan_type
FROM users
WHERE id = $1 
  AND deleted_at IS NULL 
LIMIT 1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID `json:"id"`
	Nickname  pgtype.Text `json:"nickname"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	PlanType  string      `json:"plan_type"`
}

// Retrieves a user's display profile and service plan by their UUID.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.AvatarUrl,
		&i.PlanType,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT 
    id, 
    username, 
    password_hash, 
    nickname, 
    avatar_url, 
    plan_type
FROM users
WHERE username = $1 
  AND deleted_at IS NULL 
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Nickname     pgtype.Text `json:"nickname"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	PlanType     string      `json:"plan_type"`
}

// Retrieves an active user by their username for authentication purposes.
// Only returns users who have not been soft-deleted.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Nickname,
		&i.AvatarUrl,
		&i.PlanType,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users 
SET last_login_at = NOW()
WHERE id = $1 
  AND deleted_at IS NULL
`

// Updates the last login timestamp for a specific user.
func (q *Queries) UpdateLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}
